# System Setup
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
data_source:  ./_data
port:         8000
markdown:     redcarpet
highlighter:  pygments
permalink:    pretty
baseurl:      /
paginate:     1

# Site Details
title:        Jacob Sayles
tagline:      'A personal page'
description:  'This is my personal record for art, projects, and other things I have had a hand in creating.'

# Custom vars
version:       1.0.0
facebook_url:  https://facebook.com/jsayles
linkedin_url:  https://linkedin.com/pub/jacob-sayles
github_url:    https://github.com/jsayles
twitter_url:   https://twitter.com/jacobsayles
email:     jsayles@gmail.com
