# System Setup
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
data_source:  ./_data
port:         8000
markdown:     redcarpet
highlighter:  pygments
permalink:    pretty
baseurl:      /
paginate:     1

# Setup
title:        Jacob Sayles
tagline:      'A personal blog'
description:  'This is my personal blog/porfolio/whatever for art projects and such.'
#url:          http://jacobsayles.com
url:          http://jsayles.github.io
author:
   name:      Jacob Sayles
   email:     jsayles@gmail.com

# Custom vars
version:       1.0.0
github_url:    https://github.com/jsayles
twitter_url:   https://twitter.com/jacobsayles
