# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jacob Sayles
tagline:          'A personal blog'
description:      'This is my personal blog/porfolio/whatever for art projects and the like.'
url:              http://jacobsayles.com
baseurl:          /

author:
  name:           'Jacob Sayles'
  url:            https://twitter.com/jacobsayles

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jsayles
